### ISSUE TITLE
I have an issue

### ISSUE THREAD

**Issue by lion9994** [KyroFrCode/moonlight-chrome-tizen#25]
=> ERROR [base 19/25] RUN cmake  -DCMAKE_TOOLCHAIN_FILE=/home/moonlight/emscripten-release-bundle/emsdk/fastcomp  0.4s

**Comment by OneLiberty** [comment]
You should probably give more info about what you're trying to do in order to help. 
Anyway, if you're trying to install the app just use : 
- docker run -it --rm ghcr.io/kyrofrcode/moonlight-chrome-tizen:samsung_wasm
- sdb connect TV_IP 
- sdb devices 
- tizen install -n MoonlightWasm.wgt -t DEVICE_ID

**Comment by lion9994** [comment]
> You should probably give more info about what you're trying to do in order to help. Anyway, if you're trying to install the app just use :
> 
> * docker run -it --rm ghcr.io/kyrofrcode/moonlight-chrome-tizen:samsung_wasm
> * sdb connect TV_IP
> * sdb devices
> * tizen install -n MoonlightWasm.wgt -t DEVICE_ID

I try this and i have another issue:

app_id[MoonLightS.MoonlightWasm] install failed[118, -11], reason: Author certificate not match

**Comment by OneLiberty** [comment]
Is the app already installed ? if yes uninstall it. 
Else, check that your tv is on tizen 5.5 (2020) or more. 
The app won't install on version lower than 5.5
